// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_you_have_been_practicing = "CgkIx5XJjMMIEAIQDA"; // <GPGSID>
        public const string achievement_small_progress = "CgkIx5XJjMMIEAIQCw"; // <GPGSID>
        public const string achievement_youre_a_hacker = "CgkIx5XJjMMIEAIQDQ"; // <GPGSID>
        public const string leaderboard_endless_points = "CgkIx5XJjMMIEAIQCg"; // <GPGSID>
        public const string achievement_your_first_win = "CgkIx5XJjMMIEAIQBQ"; // <GPGSID>
        public const string achievement_lets_play_statues = "CgkIx5XJjMMIEAIQCQ"; // <GPGSID>
        public const string leaderboard_hard_wins = "CgkIx5XJjMMIEAIQAQ"; // <GPGSID>
        public const string achievement_10_wins_of_any_gamemode = "CgkIx5XJjMMIEAIQBw"; // <GPGSID>
        public const string achievement_your_first_play = "CgkIx5XJjMMIEAIQBA"; // <GPGSID>
        public const string achievement_the_real_hard_way = "CgkIx5XJjMMIEAIQCA"; // <GPGSID>
        public const string achievement_5_wins_of_any_gamemode = "CgkIx5XJjMMIEAIQBg"; // <GPGSID>
        public const string leaderboard_easy_wins = "CgkIx5XJjMMIEAIQAg"; // <GPGSID>

}

